name: Deploy Microservice to EC2

on:
  push:
    branches:
      - create/dockerfile/for/aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_M }}
          username: ${{ secrets.EC2_USER_M }}
          key: ${{ secrets.EC2_SSH_KEY_M }}
          script: |
            
            docker stop create_user_microservice || true
            docker rm create_user_microservice || true
            
           
            docker pull lssalas/create_user_microservice_image
            
            
            docker run -d --name create_user_microservice \
              --env DB_USER=${{ secrets.DB_USER_M }} \
              --env DB_PASSWORD=${{ secrets.DB_PASSWORD_M }} \
              --env DB_SERVER=${{ secrets.DB_SERVER_M }} \
              --env DB_NAME=${{ secrets.DB_NAME_M }} \
              -p 5000:5000 \
              lssalas/create_user_microservice_image
